server:
  port: ${GATEWAY_SERVICE_PORT:9999}
  servlet:
    contextPath: /api

spring:
  profiles: default
#   cloud:
#     stream:
#       bindings:
#         output:
#           destination: reservations

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9191/uaa/user

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
            strategy: SEMAPHORE

spring.kafka:
  bootstrap-servers: localhost:9092

# https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/2.1.0.RC3/multi/multi__kafka_streams_binder.html
#
# defaults
spring.cloud.stream.kafka.streams.binder:
  binder:
    autoCreateTopics: false
    replicationFactor: 1
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 1000

spring.cloud.stream.bindings:
  #
  # ordersOutFallback
  orders-out-fallback:
    destination: orders
    producer.header-mode: headers