server:
  port: ${GATEWAY_SERVICE_PORT:9999}

spring:
  profiles: default
#   cloud:
#     stream:
#       bindings:
#         output:
#           destination: reservations

# security:
#   oauth2:
#     resource:
#       userInfoUri: http://localhost:9191/uaa/user

# hystrix:
#   command:
#     default:
#       execution:
#         isolation:
#           thread:
#             timeoutInMilliseconds: 70000
#           # strategy: SEMAPHORE

zuul:
  routes:
    orders:
      path: /api/v1/orders/**
      url: http://order-service/v1/orders
      # serviceId: beta-root
      # strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie

ribbon:
  eureka:
    enabled: true