server:
  port: ${GATEWAY_SERVICE_PORT:9999}
  servlet:
    contextPath: /api

spring:
  profiles: default
#   cloud:
#     stream:
#       bindings:
#         output:
#           destination: reservations

# security:
#   oauth2:
#     resource:
#       userInfoUri: http://localhost:9191/uaa/user

# hystrix:
#   command:
#     default:
#       execution:
#         isolation:
#           thread:
#             timeoutInMilliseconds: 70000
#           # strategy: SEMAPHORE