server:
  port: ${ORDER_DETAIL_SERVICE_PORT:8085}
  servlet:
    contextPath: /v1

spring:
  profiles: default    

spring.main:
  banner-mode: off

spring.kafka:
  bootstrap-servers: localhost:9092

# https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/2.1.0.RC3/multi/multi__kafka_streams_binder.html
#
# defaults
spring.cloud.stream.kafka.streams.binder:
  binder:
    autoCreateTopics: false
    replicationFactor: 1
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 1000

spring.cloud.stream.bindings:
  #
  # ordersIn
  orders-in:
    destination: orders
    consumer.header-mode: headers
  #
  # ordersInFallback
  orders-in-fallback:
    destination: orders-fallback
    producer.header-mode: headers
  #
  # order validation out
  orders-validation-out:
    destination: orders-validation
    producer.use-native-encoding: true
    producer.header-mode: headers
    content-type: application/json
  #
  # order validation in
  orders-validation-in:
    destination: orders-validation
    consumer.use-native-encoding: true
    consumer.header-mode: headers
    group: orders-validation
    content-type: application/json