server:
  port: ${ORDER_SERVICE_PORT:8084}
  servlet:
    contextPath: /v1

spring:
  profiles: default    

spring.main:
  banner-mode: off

spring.kafka:
  bootstrap-servers: localhost:9092

# https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/2.1.0.RC3/multi/multi__kafka_streams_binder.html
#
# defaults
spring.cloud.stream.kafka.streams.binder:
  binder:
    autoCreateTopics: false
    replicationFactor: 1
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 1000

spring.cloud.stream.bindings:
  #
  # ordersOut
  orders-out:
    destination: orders
    producer.header-mode: headers